### ISSUE TITLE
exclude bigdata-03

### ISSUE THREAD

**Issue by Kurt-Hetrick** [Kurt-Hetrick/CIDR_WES#27]
you're killing me smalls

**Comment by Kurt-Hetrick** [comment]
The -l should be first! (If qsub works the way qlogin worked for me)

qsub -l h=’! node’ -q prod.q,rnd.q

**Comment by Kurt-Hetrick** [comment]
done. the comment above actually does not work but,
-l 'hostname=!node'
does

**Comment by brmyers** [comment]
heads up, this has burned me before 
qsub -l h=’! node’ -q prod.q,rnd.q doesn't work because it has apostrophes.
-l 'hostname=!node' does work because it's single vertical ticks/ straight quotes

**Comment by Kurt-Hetrick** [comment]
Thanks,

I did use single quote/non-apostrophe (you'll notice in the #hpc channel they are in single quotes).

the apostrophes are from when I copied from an email and was too lazy to fix it (in here, not in the submission).

> qalter -l h='! DellR730-03' -q bigdata.q,c6320.q,lemon.q,prod.q,rnd.q 5868563
unknown resource "DellR730-03"

the problem here is the space b/w the node and ! (which was also in the email)

also the "-l" does not need to come first, but yes, you can use h=! as well as hostname=!

the two biggest things that were wrong in the email are

1. use of single ticks instead of apostrophes
2. there is no white space b/w the ! and the node name

khetric1@c6100-8> qsub -q bigdata.q,c6320.q,lemon.q,prod.q,rnd.q -l 'h=!DellR730-03' test.sh                                                                                                                    Your job 5877982 ("test.sh") has been submitted

I used
qstat -F -q bigdata.q -s r
to look at the syntax for resource allocation/request (that's how I came up with hostname).
